//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;letter&quot;:&quot;A&quot;,&quot;ordered_teams&quot;:[{&quot;id&quot;:4,&quot;country&quot;:&quot;Uruguay&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;URU&quot;,&quot;group_id&quot;:1,&quot;group_letter&quot;:&quot;A&quot;,&quot;wins&quot;:4,&quot;draws&quot;:0,&quot;losses&quot;:1,&quot;games_played&quot;:5,&quot;points&quot;:12,&quot;goals_for&quot;:7,&quot;goals_against&quot;:3,&quot;goal_differential&quot;:4},{&quot;id&quot;:1,&quot;country&quot;:&quot;Russia&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;RUS&quot;,&quot;group_id&quot;:1,&quot;group_letter&quot;:&quot;A&quot;,&quot;wins&quot;:2,&quot;draws&quot;:2,&quot;losses&quot;:1,&quot;games_played&quot;:5,&quot;points&quot;:8,&quot;goals_for&quot;:11,&quot;goals_against&quot;:7,&quot;goal_differential&quot;:4},{&quot;id&quot;:2,&quot;country&quot;:&quot;Saudi Arabia&quot;,&quot;alternate_na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Man_group_results {
            get {
                return ResourceManager.GetString("Man_group_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;venue&quot;:&quot;Moscow&quot;,&quot;location&quot;:&quot;Luzhniki Stadium&quot;,&quot;status&quot;:&quot;completed&quot;,&quot;time&quot;:&quot;full-time&quot;,&quot;fifa_id&quot;:&quot;300331503&quot;,&quot;weather&quot;:{&quot;humidity&quot;:&quot;43&quot;,&quot;temp_celsius&quot;:&quot;17&quot;,&quot;temp_farenheit&quot;:&quot;49&quot;,&quot;wind_speed&quot;:&quot;6&quot;,&quot;description&quot;:&quot;Partly Cloudy&quot;},&quot;attendance&quot;:&quot;78011&quot;,&quot;officials&quot;:[&quot;Nestor PITANA&quot;,&quot;Hernan MAIDANA&quot;,&quot;Juan Pablo BELATTI&quot;,&quot;Sandro RICCI&quot;,&quot;Massimiliano IRRATI&quot;,&quot;Carlos ASTROZA&quot;,&quot;Mauro VIGLIANO&quot;,&quot;Daniele ORSATO&quot;,&quot;Emerson DE CARVALHO&quot;],&quot;stage_name&quot;:&quot;First stage&quot;,&quot;home_team_country&quot;:&quot;Russia&quot;,&quot;away_team_country&quot;:&quot;Saudi Ar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Man_matches {
            get {
                return ResourceManager.GetString("Man_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:24,&quot;country&quot;:&quot;Korea Republic&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;KOR&quot;,&quot;group_id&quot;:6,&quot;group_letter&quot;:&quot;F&quot;,&quot;wins&quot;:1,&quot;draws&quot;:0,&quot;losses&quot;:2,&quot;games_played&quot;:3,&quot;points&quot;:3,&quot;goals_for&quot;:3,&quot;goals_against&quot;:3,&quot;goal_differential&quot;:0},{&quot;id&quot;:21,&quot;country&quot;:&quot;Germany&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;GER&quot;,&quot;group_id&quot;:6,&quot;group_letter&quot;:&quot;F&quot;,&quot;wins&quot;:1,&quot;draws&quot;:0,&quot;losses&quot;:2,&quot;games_played&quot;:3,&quot;points&quot;:3,&quot;goals_for&quot;:2,&quot;goals_against&quot;:4,&quot;goal_differential&quot;:-2},{&quot;id&quot;:20,&quot;country&quot;:&quot;Serbia&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;SRB&quot;,&quot;group_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Man_results {
            get {
                return ResourceManager.GetString("Man_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:24,&quot;country&quot;:&quot;Korea Republic&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;KOR&quot;,&quot;group_id&quot;:6,&quot;group_letter&quot;:&quot;F&quot;},{&quot;id&quot;:21,&quot;country&quot;:&quot;Germany&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;GER&quot;,&quot;group_id&quot;:6,&quot;group_letter&quot;:&quot;F&quot;},{&quot;id&quot;:20,&quot;country&quot;:&quot;Serbia&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;SRB&quot;,&quot;group_id&quot;:5,&quot;group_letter&quot;:&quot;E&quot;},{&quot;id&quot;:19,&quot;country&quot;:&quot;Costa Rica&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;CRC&quot;,&quot;group_id&quot;:5,&quot;group_letter&quot;:&quot;E&quot;},{&quot;id&quot;:25,&quot;country&quot;:&quot;Belgium&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;BEL&quot;,&quot;group_id&quot;:7,&quot;group_lette [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Man_teams {
            get {
                return ResourceManager.GetString("Man_teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;letter&quot;:&quot;A&quot;,&quot;ordered_teams&quot;:[{&quot;id&quot;:1,&quot;country&quot;:&quot;France&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;FRA&quot;,&quot;group_id&quot;:1,&quot;group_letter&quot;:&quot;A&quot;,&quot;wins&quot;:4,&quot;draws&quot;:0,&quot;losses&quot;:1,&quot;games_played&quot;:5,&quot;points&quot;:12,&quot;goals_for&quot;:10,&quot;goals_against&quot;:4,&quot;goal_differential&quot;:6},{&quot;id&quot;:3,&quot;country&quot;:&quot;Norway&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;NOR&quot;,&quot;group_id&quot;:1,&quot;group_letter&quot;:&quot;A&quot;,&quot;wins&quot;:2,&quot;draws&quot;:1,&quot;losses&quot;:2,&quot;games_played&quot;:5,&quot;points&quot;:7,&quot;goals_for&quot;:7,&quot;goals_against&quot;:7,&quot;goal_differential&quot;:0},{&quot;id&quot;:4,&quot;country&quot;:&quot;Nigeria&quot;,&quot;alternate_name&quot;:nu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Woman_group_results {
            get {
                return ResourceManager.GetString("Woman_group_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;venue&quot;:&quot;Paris&quot;,&quot;location&quot;:&quot;Parc des Princes&quot;,&quot;status&quot;:&quot;completed&quot;,&quot;time&quot;:&quot;full-time&quot;,&quot;fifa_id&quot;:&quot;300438238&quot;,&quot;weather&quot;:{&quot;humidity&quot;:&quot;78&quot;,&quot;temp_celsius&quot;:&quot;15&quot;,&quot;temp_farenheit&quot;:&quot;47&quot;,&quot;wind_speed&quot;:&quot;32&quot;,&quot;description&quot;:&quot;Cloudy&quot;},&quot;attendance&quot;:&quot;45261&quot;,&quot;officials&quot;:[&quot;Claudia UMPIERREZ&quot;,&quot;Luciana MASCARANA&quot;,&quot;Monica AMBOYA&quot;,&quot;Melissa BORJAS&quot;,&quot;Mauro VIGLIANO&quot;,&quot;Felisha MARISCAL&quot;,&quot;Jose Maria SANCHEZ&quot;,&quot;Mariana DE ALMEIDA&quot;],&quot;stage_name&quot;:&quot;First Stage&quot;,&quot;home_team_country&quot;:&quot;France&quot;,&quot;away_team_country&quot;:&quot;Korea Republic&quot;,&quot;datetime&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Woman_matches {
            get {
                return ResourceManager.GetString("Woman_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:17,&quot;country&quot;:&quot;Canada&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;CAN&quot;,&quot;group_id&quot;:5,&quot;group_letter&quot;:&quot;E&quot;,&quot;wins&quot;:2,&quot;draws&quot;:0,&quot;losses&quot;:2,&quot;games_played&quot;:4,&quot;points&quot;:6,&quot;goals_for&quot;:4,&quot;goals_against&quot;:3,&quot;goal_differential&quot;:1},{&quot;id&quot;:14,&quot;country&quot;:&quot;Scotland&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;SCO&quot;,&quot;group_id&quot;:4,&quot;group_letter&quot;:&quot;D&quot;,&quot;wins&quot;:0,&quot;draws&quot;:1,&quot;losses&quot;:2,&quot;games_played&quot;:3,&quot;points&quot;:1,&quot;goals_for&quot;:5,&quot;goals_against&quot;:7,&quot;goal_differential&quot;:-2},{&quot;id&quot;:9,&quot;country&quot;:&quot;Australia&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;AUS&quot;,&quot;group_id&quot;:3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Woman_results {
            get {
                return ResourceManager.GetString("Woman_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:17,&quot;country&quot;:&quot;Canada&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;CAN&quot;,&quot;group_id&quot;:5,&quot;group_letter&quot;:&quot;E&quot;},{&quot;id&quot;:14,&quot;country&quot;:&quot;Scotland&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;SCO&quot;,&quot;group_id&quot;:4,&quot;group_letter&quot;:&quot;D&quot;},{&quot;id&quot;:9,&quot;country&quot;:&quot;Australia&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;AUS&quot;,&quot;group_id&quot;:3,&quot;group_letter&quot;:&quot;C&quot;},{&quot;id&quot;:15,&quot;country&quot;:&quot;Argentina&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;ARG&quot;,&quot;group_id&quot;:4,&quot;group_letter&quot;:&quot;D&quot;},{&quot;id&quot;:10,&quot;country&quot;:&quot;Italy&quot;,&quot;alternate_name&quot;:null,&quot;fifa_code&quot;:&quot;ITA&quot;,&quot;group_id&quot;:3,&quot;group_letter&quot;:&quot;C&quot;}, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Woman_teams {
            get {
                return ResourceManager.GetString("Woman_teams", resourceCulture);
            }
        }
    }
}
